"""followers

Revision ID: 963f742dbc4c
Revises: 4473cab7dbd9
Create Date: 2020-02-04 12:18:39.213073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963f742dbc4c'
down_revision = '4473cab7dbd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
